communities = [
    { slug = 'python-madrid' , url = 'https://www.meetup.com/python-madrid/' },
    { slug = 'pydata-madrid' , url = 'https://www.meetup.com/pydata-madrid/' },
    # { slug = 'python-vigo' , url = 'https://www.python-vigo.es/' },
    { slug = 'python-coruña' , url = 'https://www.meetup.com/python-a-coruna/' },
    { slug = 'pydata-salamanca' , url = 'https://www.meetup.com/PyData-Salamanca/' },
    { slug = 'python-girona' , url = 'https://www.meetup.com/PythonGirona/' },
    { slug = 'pyladies-barcelona' , url = 'https://www.meetup.com/PyLadies-BCN/' },
    { slug = 'python-barcelona' , url = 'https://www.meetup.com/python-barcelona/' },
    { slug = 'pydata-mallorca' , url = 'https://www.meetup.com/PyData-Mallorca/' },
    { slug = 'python-mallorca' , url = 'https://www.meetup.com/Mallorca-Python-Meetup/' },
    { slug = 'pydata-ibiza' , url = 'https://www.meetup.com/pydata-eivissa-ibiza/' },
    { slug = 'python-sevilla' , url = 'https://www.meetup.com/Python-Sevilla/' },
    { slug = 'python-cordoba' , url = 'https://www.meetup.com/Meetup-de-Python-en-Cordoba/' },
    { slug = 'python-malaga' , url = 'https://www.meetup.com/python_malaga/' },
    { slug = 'pydata-granada' , url = 'https://www.meetup.com/pydatagrx/' },
    { slug = 'python-alicante' , url = 'https://www.meetup.com/python_alc/' },
    { slug = 'python-valencia' , url = 'https://www.meetup.com/python-valencia-meetup/' },
]
